<?php

namespace App\Http\Controllers;

require  'C:\label\eps.php';

use App\Jobs\ProductionPlanByArrayMigrationJob;
use App\Models\Client;
use BaconQrCode\Encoder\QrCode;
use Carbon\Carbon;
use DOMDocument;
use DOMXPath;
use EscposTest;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\View;
use Mike42\Escpos\EscposImage;
use Mike42\Escpos\PrintConnectors\FilePrintConnector;
use Mike42\Escpos\PrintConnectors\WindowsPrintConnector;
use Mike42\Escpos\Printer;
use SimpleSoftwareIO\QrCode\Facades\QrCode as FacadesQrCode;
use Spatie\Browsershot\Browsershot;

class ExampleController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        echo now();

        $data = [
            ['part_number' => 'BDTS28BA0                          '],
            ['part_number' => 'BDTS28BB0                          '],
            ['part_number' => 'BDTS28B0V -1                       '],
            ['part_number' => 'BDTS28B00A -AP                     '],
            ['part_number' => 'BDTS28B01                          '],
            ['part_number' => 'BDTS28B1R -AM                      '],
            ['part_number' => 'BDTS28B1Y                          '],
            ['part_number' => 'BDTS28B1Z                          '],
            ['part_number' => 'BDTS28B2U -AS                      '],
            ['part_number' => 'BDTS28B2Y                          '],
            ['part_number' => 'BDTS28B2Z                          '],
            ['part_number' => 'BDTS28B35 -P                       '],
            ['part_number' => 'BDTS28B45 -P                       '],
            ['part_number' => 'BDTS28B6X                          '],
            ['part_number' => 'BDTS28B6Y                          '],
            ['part_number' => 'BDTS3480XB -AP                     '],
            ['part_number' => 'BDTS3480XB -BP                     '],
            ['part_number' => 'BDTS34801 -P                       '],
            ['part_number' => 'BDTS34811 -P                       '],
            ['part_number' => 'BDTS34812 -P                       '],
            ['part_number' => 'BDTS3482P -AM                      '],
            ['part_number' => 'BDTS3482X                          '],
            ['part_number' => 'BDTS3482X -P                       '],
            ['part_number' => 'BDTS3482Y                          '],
            ['part_number' => 'BDTS3482Y -P                       '],
            ['part_number' => 'BDTS3483P                          '],
            ['part_number' => 'BDTS3483T -AM                      '],
            ['part_number' => 'BDTS3483X -P                       '],
            ['part_number' => 'BDTS3483Z                          '],
            ['part_number' => 'BDTS34830                          '],
            ['part_number' => 'BDTS3484P                          '],
            ['part_number' => 'BDTS3484S                          '],
            ['part_number' => 'BDTS3484UA                         '],
            ['part_number' => 'BDTS3486X                          '],
            ['part_number' => 'BDTS3486X -P                       '],
            ['part_number' => 'BDTS3486Y                          '],
            ['part_number' => 'BDTS3486Y -P                       '],
            ['part_number' => 'BDTS3488X                          '],
            ['part_number' => 'BDTS3488Y                          '],
            ['part_number' => 'BDTS3489X                          '],
            ['part_number' => 'BDTS3489Y                          '],
            ['part_number' => 'BDTS4101Z                          '],
            ['part_number' => 'BDTS4102Z                          '],
            ['part_number' => 'BDTS41020                          '],
            ['part_number' => 'BDTS41020 -1                       '],
            ['part_number' => 'BDTS41070 -1                       '],
            ['part_number' => 'BDTS41070 -2                       '],
            ['part_number' => 'BDTS41070B                         '],
            ['part_number' => 'BDTS4130XA                         '],
            ['part_number' => 'BDTS4130XA -1                      '],
            ['part_number' => 'BDTS4130XA -2                      '],
            ['part_number' => 'BDTS41300A -1                      '],
            ['part_number' => 'BDTS4302XA                         '],
            ['part_number' => 'BDTS4302XA -1                      '],
            ['part_number' => 'BDTS4302XA -2                      '],
            ['part_number' => 'BDTS43020A                         '],
            ['part_number' => 'BDTS4303XA                         '],
            ['part_number' => 'BDTS43030A -AP                     '],
            ['part_number' => 'BDTS43030A -1                      '],
            ['part_number' => 'BDTS43050A                         '],
            ['part_number' => 'BDTS4307YA                         '],
            ['part_number' => 'BDTS43070B                         '],
            ['part_number' => 'BDTS50071                          '],
            ['part_number' => 'BDTS5008L                          '],
            ['part_number' => 'BDTS5008R                          '],
            ['part_number' => 'BDTS5008X                          '],
            ['part_number' => 'BDTS50261                          '],
            ['part_number' => 'BDTS5318P                          '],
            ['part_number' => 'BDTS5318Y                          '],
            ['part_number' => 'BDTS53230A                         '],
            ['part_number' => 'BDTS5324P                          '],
            ['part_number' => 'BDTS5324RA                         '],
            ['part_number' => 'BDTS53240A                         '],
            ['part_number' => 'BDTS5325XA                         '],
            ['part_number' => 'BDTS5326P                          '],
            ['part_number' => 'BDTS53260                          '],
            ['part_number' => 'BDTS533CX -PK                      '],
            ['part_number' => 'BDTS5335P                          '],
            ['part_number' => 'BDTS534KX                          '],
            ['part_number' => 'BDTS5340P                          '],
            ['part_number' => 'BDTS5341PA                         '],
            ['part_number' => 'BDTS5341T                          '],
            ['part_number' => 'BDTS5342S                          '],
            ['part_number' => 'BDTS5342Y                          '],
            ['part_number' => 'BDTS53430 -1                       '],
            ['part_number' => 'BDTS53450                          '],
            ['part_number' => 'BDTS53460                          '],
            ['part_number' => 'BDTS5348PA                         '],
            ['part_number' => 'BDTS5348Q                          '],
            ['part_number' => 'BDTS53480                          '],
            ['part_number' => 'BDTS535Z0                          '],
            ['part_number' => 'BDTS53510                          '],
            ['part_number' => 'BDTS53510 -1                       '],
            ['part_number' => 'BDTS53580                          '],
            ['part_number' => 'BDTS5359ZA                         '],
            ['part_number' => 'BDTS53590A                         '],
            ['part_number' => 'BDTS53603A                         '],
            ['part_number' => 'BDTS5361P                          '],
            ['part_number' => 'BDTS5361XA-PK                      '],
            ['part_number' => 'BDTS5362Y                          '],
            ['part_number' => 'BDTS5363Y                          '],
            ['part_number' => 'BDTS5365P                          '],
            ['part_number' => 'BDTS5365P -1                       '],
            ['part_number' => 'BDTS53660 -PK                      '],
            ['part_number' => 'BDTS538BX                          '],
            ['part_number' => 'BDTS5381Z                          '],
            ['part_number' => 'BDTS5383R                          '],
            ['part_number' => 'BDTS5383ZA                         '],
            ['part_number' => 'BDTS53830                          '],
            ['part_number' => 'BDTS5389X                          '],
            ['part_number' => 'BDTS539B0                          '],
            ['part_number' => 'BDTS539EX                          '],
            ['part_number' => 'BDTS5391P                          '],
            ['part_number' => 'BDTS5391Z                          '],
            ['part_number' => 'BDTS5392Y                          '],
            ['part_number' => 'BDTS5395Q                          '],
            ['part_number' => 'BDTS5395X                          '],
            ['part_number' => 'BDTS53970                          '],
            ['part_number' => 'BDTS53990                          '],
            ['part_number' => 'BDTS5418P                          '],
            ['part_number' => 'BDTS5418Y                          '],
            ['part_number' => 'BDTS5418Y -1                       '],
            ['part_number' => 'BDTS542EX                          '],
            ['part_number' => 'BDTS5422Y                          '],
            ['part_number' => 'BDTS54230A                         '],
            ['part_number' => 'BDTS5424PA                         '],
            ['part_number' => 'BDTS5424RB                         '],
            ['part_number' => 'BDTS54240B                         '],
            ['part_number' => 'BDTS5425XA                         '],
            ['part_number' => 'BDTS5426P                          '],
            ['part_number' => 'BDTS54260                          '],
            ['part_number' => 'BDTS543CX -PK                      '],
            ['part_number' => 'BDTS5431R                          '],
            ['part_number' => 'BDTS5435P                          '],
            ['part_number' => 'BDTS5435Q                          '],
            ['part_number' => 'BDTS5442S                          '],
            ['part_number' => 'BDTS5442S -1                       '],
            ['part_number' => 'BDTS5444X                          '],
            ['part_number' => 'BDTS54470                          '],
            ['part_number' => 'BDTS545Z0                          '],
            ['part_number' => 'BDTS54560                          '],
            ['part_number' => 'BDTS54580                          '],
            ['part_number' => 'BDTS54590                          '],
            ['part_number' => 'BDTS54603A                         '],
            ['part_number' => 'BDTS5461P                          '],
            ['part_number' => 'BDTS5461XA-PK                      '],
            ['part_number' => 'BDTS5462Y                          '],
            ['part_number' => 'BDTS5463Y                          '],
            ['part_number' => 'BDTS5465P                          '],
            ['part_number' => 'BDTS5465P -1                       '],
            ['part_number' => 'BDTS54660 -PK                      '],
            ['part_number' => 'BDTS5472X                          '],
            ['part_number' => 'BDTS5472Z                          '],
            ['part_number' => 'BDTS548BX                          '],
            ['part_number' => 'BDTS5481Z                          '],
            ['part_number' => 'BDTS5482Y -PK                      '],
            ['part_number' => 'BDTS5483PA                         '],
            ['part_number' => 'BDTS5483R                          '],
            ['part_number' => 'BDTS5483ZA                         '],
            ['part_number' => 'BDTS54830                          '],
            ['part_number' => 'BDTS549A0                          '],
            ['part_number' => 'BDTS5495Q                          '],
            ['part_number' => 'BDTS5495X                          '],
            ['part_number' => 'BDTS54990                          '],
            ['part_number' => 'BDTS56H1P                          '],
            ['part_number' => 'BDTS56H1XA                         '],
            ['part_number' => 'BDTS56H1XA -AP                     '],
            ['part_number' => 'BDTS56H1Y                          '],
            ['part_number' => 'BDTS56H30A                         '],
            ['part_number' => 'BDTS56H30A -1                      '],
            ['part_number' => 'BDTS58191 -SB                      '],
            ['part_number' => 'BDTS58192 -SB                      '],
            ['part_number' => 'BDTS59191 -SB                      '],
            ['part_number' => 'BDTS59192 -SB                      '],
            ['part_number' => 'BDTS6045A                          '],
            ['part_number' => 'BDTS6046A                          '],
            ['part_number' => 'BDTS605BA                          '],
            ['part_number' => 'BDTS6054A                          '],
            ['part_number' => 'BDTS6055A                          '],
            ['part_number' => 'BDTS6056A                          '],
            ['part_number' => 'BDTS6058A                          '],
            ['part_number' => 'BDTS7003X -PK                      '],
            ['part_number' => 'BDTS701CP                          '],
            ['part_number' => 'BDTS7012Z                          '],
            ['part_number' => 'BDTS7018P                          '],
            ['part_number' => 'BDTS7018X                          '],
            ['part_number' => 'BDTS70260 -PK                      '],
            ['part_number' => 'BDTS70260 -1                       '],
            ['part_number' => 'BDTS7027Q                          '],
            ['part_number' => 'BDTS7027Z                          '],
            ['part_number' => 'BDTS70270                          '],
            ['part_number' => 'BDTS70280 -PK                      '],
            ['part_number' => 'BDTS70361 -SB                      '],
            ['part_number' => 'BDTS7051Y                          '],
            ['part_number' => 'BDTS7051Y-1                        '],
            ['part_number' => 'BDTS70570                          '],
            ['part_number' => 'BDTS7066X -PK                      '],
            ['part_number' => 'BDTS7066X -1                       '],
            ['part_number' => 'BDTS7103X -PK                      '],
            ['part_number' => 'BDTS7105X                          '],
            ['part_number' => 'BDTS711CP                          '],
            ['part_number' => 'BDTS7112Z                          '],
            ['part_number' => 'BDTS7112Z -1                       '],
            ['part_number' => 'BDTS7118P                          '],
            ['part_number' => 'BDTS7118X                          '],
            ['part_number' => 'BDTS7127Q                          '],
            ['part_number' => 'BDTS7127Z                          '],
            ['part_number' => 'BDTS71270                          '],
            ['part_number' => 'BDTS71280 -PK                      '],
            ['part_number' => 'BDTS71361 -SB                      '],
            ['part_number' => 'BDTS71570                          '],
            ['part_number' => 'BDTS7163Y                          '],
            ['part_number' => 'BDTS72191 -SB                      '],
            ['part_number' => 'BDTS72192 -SB                      '],
            ['part_number' => 'BDTS73191 -SB                      '],
            ['part_number' => 'BDTS73192 -SB                      '],
            ['part_number' => 'BDTT6049A                          '],
            ['part_number' => 'BDTT7062X                          '],
            ['part_number' => 'BDTT7062Z                          '],
            ['part_number' => 'BDTT7062Z -1                       '],
            ['part_number' => 'BDTT7063P                          '],
            ['part_number' => 'BDTT7063X                          '],
            ['part_number' => 'BDTT7063Z                          '],
            ['part_number' => 'BDTT7162X                          '],
            ['part_number' => 'BDTT7162Z                          '],
            ['part_number' => 'BDTT7162Z -1                       '],
            ['part_number' => 'BDTT7163Z                          '],
            ['part_number' => 'BDTV4302XA                         '],
            ['part_number' => 'BDTV4302XA -1                      '],
            ['part_number' => 'BDTV4302XA -2                      '],
            ['part_number' => 'BDTV43020A                         '],
            ['part_number' => 'BDTV43030A -AP                     '],
            ['part_number' => 'BDTV43030A -1                      '],
            ['part_number' => 'BDTV5342PA                         '],
            ['part_number' => 'BDTV53420                          '],
            ['part_number' => 'BDTV53430                          '],
            ['part_number' => 'BDTV53430 -2                       '],
            ['part_number' => 'BDWK3480XB -AP                     '],
            ['part_number' => 'BDWK3480XB -BP                     '],
            ['part_number' => 'BDWK34811A -P                      '],
            ['part_number' => 'BDWK34812 -P                       '],
            ['part_number' => 'BDWK3482P -AM                      '],
            ['part_number' => 'BDWK3482X                          '],
            ['part_number' => 'BDWK3482X -P                       '],
            ['part_number' => 'BDWK3482Y                          '],
            ['part_number' => 'BDWK3482Y -P                       '],
            ['part_number' => 'BDWK3483T -AM                      '],
            ['part_number' => 'BDWK3483X -P                       '],
            ['part_number' => 'BDWK3484S                          '],
            ['part_number' => 'BDWK3486X                          '],
            ['part_number' => 'BDWK3486Y                          '],
            ['part_number' => 'BDWK4302X                          '],
            ['part_number' => 'BDWK4302X -1                       '],
            ['part_number' => 'BDWK4302X -2                       '],
            ['part_number' => 'BDWK43020                          '],
            ['part_number' => 'BDWK4303X                          '],
            ['part_number' => 'BDWK43030 -AP                      '],
            ['part_number' => 'BDWK43030 -1                       '],
            ['part_number' => 'BDWK43050A                         '],
            ['part_number' => 'BDWK4307YA                         '],
            ['part_number' => 'BDWK43070B                         '],
            ['part_number' => 'BDWP28BA0                          '],
            ['part_number' => 'BDWP28BB0                          '],
            ['part_number' => 'BDWP28B0VA -1                      '],
            ['part_number' => 'BDWP28B00B -AP                     '],
            ['part_number' => 'BDWP28B01                          '],
            ['part_number' => 'BDWP28B1R -AM                      '],
            ['part_number' => 'BDWP28B1XA                         '],
            ['part_number' => 'BDWP28B1Y                          '],
            ['part_number' => 'BDWP28B1Z                          '],
            ['part_number' => 'BDWP28B2U -AS                      '],
            ['part_number' => 'BDWP28B2XA                         '],
            ['part_number' => 'BDWP28B2Y                          '],
            ['part_number' => 'BDWP28B2Z                          '],
            ['part_number' => 'BDWP28B6X                          '],
            ['part_number' => 'BDWP28B6Y                          '],
            ['part_number' => 'BDWP28850 -AP                      '],
            ['part_number' => 'BDWP28850 -BP                      '],
            ['part_number' => 'BDWP3480XA -AP                     '],
            ['part_number' => 'BDWP3480XA -BP                     '],
            ['part_number' => 'BDWP3484S                          '],
            ['part_number' => 'BDWP5391P                          '],
            ['part_number' => 'BJS75342Y                          '],
            ['part_number' => 'DA6A50071                          '],
            ['part_number' => 'DA6A50080                          '],
            ['part_number' => 'DA6A50090                          '],
            ['part_number' => 'DA6A531E0                          '],
            ['part_number' => 'DA6A5312P                          '],
            ['part_number' => 'DA6A5312Q                          '],
            ['part_number' => 'DA6A5312X -PK                      '],
            ['part_number' => 'DA6A532CY                          '],
            ['part_number' => 'DA6A5320Y                          '],
            ['part_number' => 'DA6A5322P                          '],
            ['part_number' => 'DA6A5322Y                          '],
            ['part_number' => 'DA6A53220                          '],
            ['part_number' => 'DA6A5323P                          '],
            ['part_number' => 'DA6A5324P                          '],
            ['part_number' => 'DA6A5324Y                          '],
            ['part_number' => 'DA6A5325X                          '],
            ['part_number' => 'DA6A53260                          '],
            ['part_number' => 'DA6A5327Y                          '],
            ['part_number' => 'DA6A53280                          '],
            ['part_number' => 'DA6A5333X                          '],
            ['part_number' => 'DA6A5339P                          '],
            ['part_number' => 'DA6A5341P                          '],
            ['part_number' => 'DA6A5341Q                          '],
            ['part_number' => 'DA6A5343Z -1                       '],
            ['part_number' => 'DA6A5343ZA                         '],
            ['part_number' => 'DA6A53430A                         '],
            ['part_number' => 'DA6A535DX                          '],
            ['part_number' => 'DA6A53510                          '],
            ['part_number' => 'DA6A53550                          '],
            ['part_number' => 'DA6A5356Y                          '],
            ['part_number' => 'DA6A5356Y -1                       '],
            ['part_number' => 'DA6A5359Z                          '],
            ['part_number' => 'DA6A5361P                          '],
            ['part_number' => 'DA6A5362Z                          '],
            ['part_number' => 'DA6A5365P                          '],
            ['part_number' => 'DA6A53660 -PK                      '],
            ['part_number' => 'DA6A53760A                         '],
            ['part_number' => 'DA6A53770                          '],
            ['part_number' => 'DA6A53830                          '],
            ['part_number' => 'DA6A53830 -1                       '],
            ['part_number' => 'DA6A5389X -PK                      '],
            ['part_number' => 'DA6A539M0                          '],
            ['part_number' => 'DA6A539M0 -1                       '],
            ['part_number' => 'DA6A5390W                          '],
            ['part_number' => 'DA6A5391Z                          '],
            ['part_number' => 'DA6A5392W                          '],
            ['part_number' => 'DA6A5392W -1                       '],
            ['part_number' => 'DA6A5392W -2                       '],
            ['part_number' => 'DA6A5395X                          '],
            ['part_number' => 'DA6A5395Y                          '],
            ['part_number' => 'DA6A53970                          '],
            ['part_number' => 'DA6A541E0                          '],
            ['part_number' => 'DA6A5412P                          '],
            ['part_number' => 'DA6A5412Q                          '],
            ['part_number' => 'DA6A5412X -PK                      '],
            ['part_number' => 'DA6A542CY                          '],
            ['part_number' => 'DA6A5420Y                          '],
            ['part_number' => 'DA6A5422X                          '],
            ['part_number' => 'DA6A5422Y                          '],
            ['part_number' => 'DA6A54220                          '],
            ['part_number' => 'DA6A5423P                          '],
            ['part_number' => 'DA6A5424P                          '],
            ['part_number' => 'DA6A5425X                          '],
            ['part_number' => 'DA6A54260                          '],
            ['part_number' => 'DA6A5427Y                          '],
            ['part_number' => 'DA6A54280                          '],
            ['part_number' => 'DA6A5433X                          '],
            ['part_number' => 'DA6A5435X                          '],
            ['part_number' => 'DA6A5439P                          '],
            ['part_number' => 'DA6A54410                          '],
            ['part_number' => 'DA6A54410 -1                       '],
            ['part_number' => 'DA6A545DX                          '],
            ['part_number' => 'DA6A5456Y                          '],
            ['part_number' => 'DA6A5456Y -1                       '],
            ['part_number' => 'DA6A54560                          '],
            ['part_number' => 'DA6A5460P                          '],
            ['part_number' => 'DA6A5482X -PK                      '],
            ['part_number' => 'DA6A54830                          '],
            ['part_number' => 'DA6A54830 -1                       '],
            ['part_number' => 'DA6A5489X -PK                      '],
            ['part_number' => 'DA6A549M0                          '],
            ['part_number' => 'DA6A549M0 -1                       '],
            ['part_number' => 'DA6A5494Z                          '],
            ['part_number' => 'DA6A5495X                          '],
            ['part_number' => 'DA6A5495Y                          '],
            ['part_number' => 'DA6A54970                          '],
            ['part_number' => 'DA6A56D20                          '],
            ['part_number' => 'DA6A56H00 -AS                      '],
            ['part_number' => 'DA6A56H00 -PA                      '],
            ['part_number' => 'DA6A56H1P                          '],
            ['part_number' => 'DA6A56H10                          '],
            ['part_number' => 'DA6A56H20                          '],
            ['part_number' => 'DA6A70T8P                          '],
            ['part_number' => 'DA6A70090                          '],
            ['part_number' => 'DA6A7014X                          '],
            ['part_number' => 'DA6A7017Y                          '],
            ['part_number' => 'DA6A7017Y -1                       '],
            ['part_number' => 'DA6A7027P                          '],
            ['part_number' => 'DA6A70470                          '],
            ['part_number' => 'DA6A7066X -PK                      '],
            ['part_number' => 'DA6A71T8P                          '],
            ['part_number' => 'DA6A7114X                          '],
            ['part_number' => 'DA6A7117Y                          '],
            ['part_number' => 'DA6A7117Y -1                       '],
            ['part_number' => 'DA6A7119Z                          '],
            ['part_number' => 'DA6A7127P                          '],
            ['part_number' => 'DA6B53430A                         '],
            ['part_number' => 'DA6B54650C-PK                      '],
            ['part_number' => 'DA6C58191 -SB                      '],
            ['part_number' => 'DA6C59191 -SB                      '],
            ['part_number' => 'DA6C72191 -SB                      '],
            ['part_number' => 'DA6C73191 -SB                      '],
            ['part_number' => 'DA7H28B01 -BD                      '],
            ['part_number' => 'DA7H28B10                          '],
            ['part_number' => 'DA7H28B11 -BD                      '],
            ['part_number' => 'DA7H28B11 -BE                      '],
            ['part_number' => 'DA7H28B20                          '],
            ['part_number' => 'DA7H28B21 -BD                      '],
            ['part_number' => 'DA7H28B21 -BE                      '],
            ['part_number' => 'DA7H34310                          '],
            ['part_number' => 'DA7H34310 -PA                      '],
            ['part_number' => 'DA7H34360                          '],
            ['part_number' => 'DA7H34360 -PA                      '],
            ['part_number' => 'DA7H3480X -AS                      '],
            ['part_number' => 'DA7H3481X                          '],
            ['part_number' => 'DA7H34810                          '],
            ['part_number' => 'DA7H3482X                          '],
            ['part_number' => 'DA7H3482X -1                       '],
            ['part_number' => 'DA7H3482Y                          '],
            ['part_number' => 'DA7H3482Y -1                       '],
            ['part_number' => 'DA7H3483X                          '],
            ['part_number' => 'DA7H3483Y                          '],
            ['part_number' => 'DA7H34830                          '],
            ['part_number' => 'DA7H34840                          '],
            ['part_number' => 'DA7H44050A                         '],
            ['part_number' => 'DA7R43030 -AS                      '],
            ['part_number' => 'DA7R43030 -PA                      '],
            ['part_number' => 'DA7S43030A-AS                      '],
            ['part_number' => 'DA7S43030A-PA                      '],
            ['part_number' => 'DA8A72192 -SB                      '],
            ['part_number' => 'DB7P7051P                          '],
            ['part_number' => 'DB7P7051Y                          '],
            ['part_number' => 'DB7P7052P                          '],
            ['part_number' => 'DB7P7118X                          '],
            ['part_number' => 'DD1B28B00A-AS                      '],
            ['part_number' => 'DD1B28B00A-PA                      '],
            ['part_number' => 'DD1B28B3P                          '],
            ['part_number' => 'DD1B28B30                          '],
            ['part_number' => 'DD1B28B4P                          '],
            ['part_number' => 'DD1B28B40                          '],
            ['part_number' => 'DGH928BA0                          '],
            ['part_number' => 'DGH928BB0                          '],
            ['part_number' => 'DGH928B0V -1                       '],
            ['part_number' => 'DGH928B00 -AP                      '],
            ['part_number' => 'DGH928B01                          '],
            ['part_number' => 'DGH928B1R -AM                      '],
            ['part_number' => 'DGH928B1Y                          '],
            ['part_number' => 'DGH928B1Z                          '],
            ['part_number' => 'DGH928B2U -AS                      '],
            ['part_number' => 'DGH928B2Y                          '],
            ['part_number' => 'DGH928B2Z                          '],
            ['part_number' => 'DGH928B5X                          '],
            ['part_number' => 'DGH928B5Y                          '],
            ['part_number' => 'DGH928B6X                          '],
            ['part_number' => 'DGH928B6Y                          '],
            ['part_number' => 'DGH934310A -AP                     '],
            ['part_number' => 'DGH934310A -AS                     '],
            ['part_number' => 'DGH934360A -AP                     '],
            ['part_number' => 'DGH934360A -AS                     '],
            ['part_number' => 'DGH94303XB                         '],
            ['part_number' => 'DGH95008L                          '],
            ['part_number' => 'DGH95008R                          '],
            ['part_number' => 'DGH95008X                          '],
            ['part_number' => 'DGH95312Z                          '],
            ['part_number' => 'DGH953230                          '],
            ['part_number' => 'DGH95325X                          '],
            ['part_number' => 'DGH95326P                          '],
            ['part_number' => 'DGH953260                          '],
            ['part_number' => 'DGH95329Y                          '],
            ['part_number' => 'DGH953510                          '],
            ['part_number' => 'DGH953510 -1                       '],
            ['part_number' => 'DGH953520                          '],
            ['part_number' => 'DGH953580                          '],
            ['part_number' => 'DGH953590                          '],
            ['part_number' => 'DGH9537YXA                         '],
            ['part_number' => 'DGH9537Y0A                         '],
            ['part_number' => 'DGH95372XA                         '],
            ['part_number' => 'DGH95372Z                          '],
            ['part_number' => 'DGH95381Z                          '],
            ['part_number' => 'DGH95383P                          '],
            ['part_number' => 'DGH95383R                          '],
            ['part_number' => 'DGH95393XA                         '],
            ['part_number' => 'DGH95412Z                          '],
            ['part_number' => 'DGH9542EX                          '],
            ['part_number' => 'DGH954230                          '],
            ['part_number' => 'DGH95425X                          '],
            ['part_number' => 'DGH95426P                          '],
            ['part_number' => 'DGH954260                          '],
            ['part_number' => 'DGH95429Y                          '],
            ['part_number' => 'DGH954570                          '],
            ['part_number' => 'DGH954580                          '],
            ['part_number' => 'DGH954590                          '],
            ['part_number' => 'DGH9547YL                          '],
            ['part_number' => 'DGH9547YXA                         '],
            ['part_number' => 'DGH9547Y0A                         '],
            ['part_number' => 'DGH95472XA                         '],
            ['part_number' => 'DGH95472Z                          '],
            ['part_number' => 'DGH95481Z                          '],
            ['part_number' => 'DGH95483P                          '],
            ['part_number' => 'DGH95483R                          '],
            ['part_number' => 'DGH958191 -SB                      '],
            ['part_number' => 'DGH959191 -SB                      '],
            ['part_number' => 'DGH96045P                          '],
            ['part_number' => 'DGH970T3Q                          '],
            ['part_number' => 'DGH970T3S                          '],
            ['part_number' => 'DGH970T30                          '],
            ['part_number' => 'DGH970040                          '],
            ['part_number' => 'DGH97005X                          '],
            ['part_number' => 'DGH97012ZA                         '],
            ['part_number' => 'DGH970190 -1                       '],
            ['part_number' => 'DGH970260 -PK                      '],
            ['part_number' => 'DGH970260 -1                       '],
            ['part_number' => 'DGH97027Q                          '],
            ['part_number' => 'DGH97027Z                          '],
            ['part_number' => 'DGH970280 -PK                      '],
            ['part_number' => 'DGH97063Y                          '],
            ['part_number' => 'DGH97065P                          '],
            ['part_number' => 'DGH97065Q                          '],
            ['part_number' => 'DGH97066X -PK                      '],
            ['part_number' => 'DGH97066X -1                       '],
            ['part_number' => 'DGH970760                          '],
            ['part_number' => 'DGH970770                          '],
            ['part_number' => 'DGH971T3Q                          '],
            ['part_number' => 'DGH971T3S                          '],
            ['part_number' => 'DGH971T30                          '],
            ['part_number' => 'DGH971040                          '],
            ['part_number' => 'DGH97105X                          '],
            ['part_number' => 'DGH97112ZA                         '],
            ['part_number' => 'DGH971260 -PK                      '],
            ['part_number' => 'DGH971260 -1                       '],
            ['part_number' => 'DGH97127Q                          '],
            ['part_number' => 'DGH97127Z                          '],
            ['part_number' => 'DGH971280 -PK                      '],
            ['part_number' => 'DGH97163Y                          '],
            ['part_number' => 'DGH97165P                          '],
            ['part_number' => 'DGH97165Q                          '],
            ['part_number' => 'DGH972191 -SB                      '],
            ['part_number' => 'DGH972192 -SB                      '],
            ['part_number' => 'DGH973191 -SB                      '],
            ['part_number' => 'DGH973192 -SB                      '],
            ['part_number' => 'DGJ17062X                          '],
            ['part_number' => 'DGJ17062Z                          '],
            ['part_number' => 'DGJ17062Z -1                       '],
            ['part_number' => 'DGJ17063X                          '],
            ['part_number' => 'DGJ17162X                          '],
            ['part_number' => 'DGJ17162Z                          '],
            ['part_number' => 'DGJ17162Z -1                       '],
            ['part_number' => 'DGJ24302X                          '],
            ['part_number' => 'DGJ24302X -1                       '],
            ['part_number' => 'DGJ24302X -2                       '],
            ['part_number' => 'DGJ243020B                         '],
            ['part_number' => 'DGJ243030 -1                       '],
            ['part_number' => 'DGJ243030B -AP                     '],
            ['part_number' => 'DGJ428BA0                          '],
            ['part_number' => 'DGJ428BB0                          '],
            ['part_number' => 'DGJ428B0V -1                       '],
            ['part_number' => 'DGJ428B00 -AP                      '],
            ['part_number' => 'DGJ428B01                          '],
            ['part_number' => 'DGJ428B1R -AM                      '],
            ['part_number' => 'DGJ428B1X                          '],
            ['part_number' => 'DGJ428B1Y                          '],
            ['part_number' => 'DGJ428B1Z                          '],
            ['part_number' => 'DGJ428B2U -AS                      '],
            ['part_number' => 'DGJ428B2X                          '],
            ['part_number' => 'DGJ428B2Y                          '],
            ['part_number' => 'DGJ428B2Z                          '],
            ['part_number' => 'DGJ428B6X                          '],
            ['part_number' => 'DGJ428B6Y                          '],
            ['part_number' => 'DGJ428850 -AP                      '],
            ['part_number' => 'DGJ428850 -BP                      '],
            ['part_number' => 'DGJ47075P                          '],
            ['part_number' => 'DGJ64302X                          '],
            ['part_number' => 'DGJ64302X -1                       '],
            ['part_number' => 'DGJ64302X -2                       '],
            ['part_number' => 'DGJ643020                          '],
            ['part_number' => 'DGJ643030 -AP                      '],
            ['part_number' => 'DGJ643030 -1                       '],
            ['part_number' => 'DGJ85395Q                          '],
            ['part_number' => 'DGJ85495Q                          '],
            ['part_number' => 'DGK928BA0                          '],
            ['part_number' => 'DGK928BB0                          '],
            ['part_number' => 'DGK928B0V -1                       '],
            ['part_number' => 'DGK928B00 -AP                      '],
            ['part_number' => 'DGK928B01                          '],
            ['part_number' => 'DGK928B1R -AM                      '],
            ['part_number' => 'DGK928B1Y                          '],
            ['part_number' => 'DGK928B1Z                          '],
            ['part_number' => 'DGK928B2U -AS                      '],
            ['part_number' => 'DGK928B2Y                          '],
            ['part_number' => 'DGK928B2Z                          '],
            ['part_number' => 'DGK928B6X                          '],
            ['part_number' => 'DGK928B6Y                          '],
            ['part_number' => 'DGK934310A -AP                     '],
            ['part_number' => 'DGK934310A -AS                     '],
            ['part_number' => 'DGK934360A-AP                      '],
            ['part_number' => 'DGK934360A-AS                      '],
            ['part_number' => 'PEP8104AX -1                       '],
            ['part_number' => 'PEP8104AX -2                       '],
            ['part_number' => 'PEP8104A0                          '],
            ['part_number' => 'PEP8104A0 -1                       '],
            ['part_number' => 'PEP8104BX                          '],
            ['part_number' => 'PEP8104BZ                          '],
            ['part_number' => 'PEP81040X                          '],
            ['part_number' => 'PEP81040X -1                       '],
            ['part_number' => 'PEP810400                          '],
            ['part_number' => 'PX131040X                          '],
            ['part_number' => 'PX131040X -1                       '],
            ['part_number' => 'P54G10400A-AS                      '],
            ['part_number' => 'P54G10400A-PA                      '],
        ];

        ProductionPlanByArrayMigrationJob::dispatch($data);

    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}
